url: https://mazhar266.github.io
baseurl: /portfolio

# Site settings
title: iAmMaze
email: info@mazharahmed.me
description: "ZCE, Full Stack LAMP, Python and MEAN developer, Ruby & JavaEE Lover, Payment Gateway Expert. More than 10 years as a tech leader."


# Team names, titles and social links
people:
- name: Trin Salaloy
  pic: 1
  position: MadeFreshly Inc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Steve Wong
  pic: 2
  position: Joonomy Inc
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tarique Imam
  pic: 3
  position: ST Solutions International LLC
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/humblemaze
  - title: facebook
    url: https://facebook.com/humblemaze
  - title: stack-overflow
    url: https://stackoverflow.com/users/288078/mazhar-ahmed
  - title: bitbucket
    url: https://bitbucket.org/mazhar266
  - title: github
    url: https://github.com/mazhar266

# Postal address (add as many lines as necessary)
address:
  - line: Kaderabad Housing
  - line: Mohammadpur, Dhaka 1207

# Build settings
markdown: kramdown
permalink: pretty
